#!/system/bin/sh

# Pixel Canary pif.prop generator
# Adapted from https://github.com/osm0sis/PlayIntegrityFork by @osm0sis
# Modified by @MeowDump

FLAG_DIR="${PIF_FLAG_DIR:-/data/adb/Box-Brain/PIF}"
mkdir -p "$FLAG_DIR" 2>/dev/null

# Check flag files
[ -f "$FLAG_DIR/advanced" ]  && ARGS="-a"
[ -f "$FLAG_DIR/strong" ]    && FORCE_STRONG=1
[ -f "$FLAG_DIR/match" ]     && FORCE_MATCH=1
[ -f "$FLAG_DIR/verbose" ]   && VERBOSE_MODE=1
[ -f "$FLAG_DIR/skip_json" ] && SKIP_JSON=1

[ "$VERBOSE_MODE" = 1 ] && set -x

case "$0" in
  *.sh) DIR="$0";;
  *) DIR="$(lsof -p $$ 2>/dev/null | grep -o '/.*osm0sis.sh$')";;
esac
DIR=$(dirname "$(readlink -f "$DIR")")

die() { echo "\nError: $@!"; exit 1; }
die_bb() { die "$@, install busybox"; }
warn() { echo "\nWarning: $@!"; }

export_json_from_prop() {
  [ "$SKIP_JSON" = 1 ] && return 0
  local flag_file="/data/adb/Box-Brain/json"
  local prop_file="/data/adb/modules/playintegrityfix/custom.pif.prop"
  local out_json="/sdcard/meow.json"

  [ ! -f "$flag_file" ] && return 0
  [ ! -f "$prop_file" ] && return 0

  local released_on=""
  local expiry_date=""
  local first=1

  echo "{" > "$out_json"

  while IFS= read -r line; do
    case "$line" in
      "# Released On:"*)
        released_on="${line#\# Released On: }"
        continue
        ;;
      "# Estimated Expiry:"*)
        expiry_date="${line#\# Estimated Expiry: }"
        continue
        ;;
      ""|\#*) continue ;;
    esac

    case "$line" in
      *=*)
        local key="${line%%=*}"
        local val="${line#*=}"
        key="${key#\*.}"
        key="${key#\*}"
        case "$key" in
          build.id) key="BUILD.ID" ;;
          security_patch) key="SECURITY_PATCH" ;;
          api_level) key="API_LEVEL" ;;
        esac
        val="${val//\"/\\\"}"
        [ "$first" -eq 0 ] && echo "," >> "$out_json"
        first=0
        printf '  "%s": "%s"' "$key" "$val" >> "$out_json"
        ;;
    esac
  done < "$prop_file"

  echo "" >> "$out_json"
  echo "}" >> "$out_json"
  {
    [ -n "$released_on" ] && echo "// Released On: $released_on"
    [ -n "$expiry_date" ] && echo "// Estimated Expiry: $expiry_date"
    echo "// Generated by IntegrityBox on $(date '+%Y-%m-%d')"
  } >> "$out_json"
  chmod 0644 "$out_json"
}

find_busybox() {
  [ -n "$BUSYBOX" ] && return 0
  local path
  for path in /data/adb/modules/busybox-ndk/system/*/busybox /data/adb/magisk/busybox /data/adb/ksu/bin/busybox /data/adb/ap/bin/busybox; do
    [ -f "$path" ] && BUSYBOX="$path" && return 0
  done
  return 1
}

if ! which wget >/dev/null || grep -q "wget-curl" $(which wget); then
  if ! find_busybox; then
    die_bb "wget not found"
  elif $BUSYBOX ping -c1 -s2 android.com 2>&1 | grep -q "bad address"; then
    die_bb "wget broken"
  else
    wget() { $BUSYBOX wget "$@"; }
  fi
fi

if date -D '%s' -d "$(date '+%s')" 2>&1 | grep -qE "bad date|invalid option"; then
  if ! find_busybox; then
    die_bb "date broken"
  else
    date() { $BUSYBOX date "$@"; }
  fi
fi

if ! echo "A\nB" | grep -m1 -A1 "A" | grep -q "B"; then
  if ! find_busybox; then
    die_bb "grep broken"
  else
    grep() { $BUSYBOX grep "$@"; }
  fi
fi

if [ "$DIR" = /data/adb/modules/playintegrityfix ]; then
  DIR=$DIR/osm0sis
  mkdir -p $DIR
fi
cd "$DIR"

WGET_Q="-q"
[ "$VERBOSE_MODE" = 1 ] && WGET_Q=""

echo " ➤ Fetching Pixel Beta device list"
wget $WGET_Q -T 10 -O PIXEL_VERSIONS_HTML --no-check-certificate "https://developer.android.com/about/versions" || die "Failed to fetch versions page"
LATEST_BETA=$(grep -B4 -A2 'data-icon=\"preview' PIXEL_VERSIONS_HTML | grep -o 'href="/about/versions/.*[0-9]"' | cut -d\" -f2)
[ "$LATEST_BETA" ] || LATEST_BETA=$(grep -oE 'href="/about/versions/[0-9]{2}"' PIXEL_VERSIONS_HTML | cut -d\" -f2 | sort -ru | head -n1)
[ -z "$LATEST_BETA" ] && die "Could not find latest beta version page"

wget $WGET_Q -T 10 -O PIXEL_LATEST_HTML --no-check-certificate "https://developer.android.com$LATEST_BETA" || die "Failed to fetch version page"
wget $WGET_Q -T 10 -O PIXEL_FI_HTML --no-check-certificate "https://developer.android.com$(grep -o 'href=".*download.*"' PIXEL_LATEST_HTML | grep -v 'ota' | cut -d\" -f2 | sort -ru | head -n1)" || die "Failed to fetch factory image page"
wget $WGET_Q -T 10 -O PIXEL_OTA_HTML --no-check-certificate "https://developer.android.com$(grep -o 'href=".*download-ota.*"' PIXEL_LATEST_HTML | cut -d\" -f2 | sort -ru | head -n1)" || die "Failed to fetch OTA page"

SRC=FI
[ "$(grep 'tr id=' PIXEL_FI_HTML | sed 's;.*<tr id=\"\(.*\)\">.*;\1;' | wc -w)" -lt "$(grep 'tr id=' PIXEL_OTA_HTML | sed 's;.*<tr id=\"\(.*\)\">.*;\1;' | wc -w)" ] && SRC=OTA
MODEL_LIST="$(grep -A1 'tr id=' PIXEL_${SRC}_HTML | grep 'td' | sed 's;.*<td>\(.*\)</td>;\1;')"
PRODUCT_LIST="$(grep 'tr id=' PIXEL_${SRC}_HTML | sed 's;.*<tr id=\"\(.*\)\">;\1_beta;')"
DEVICE_COUNT=$(echo "$PRODUCT_LIST" | wc -w)
echo " ➤ Found $DEVICE_COUNT beta-enrolled devices"
echo " "

if [ "$FORCE_MATCH" ]; then
  DEVICE="$(getprop ro.product.device)"
  case "$(echo ' '$PRODUCT_LIST' ')" in
    *" ${DEVICE}_beta "*)
      MODEL="$(getprop ro.product.model)"
      PRODUCT="${DEVICE}_beta"
      ;;
  esac
fi

echo " ➤ Selecting Pixel Beta device"
if [ -z "$PRODUCT" ]; then
  set_random_beta() {
    local list_count="$(echo "$MODEL_LIST" | wc -l)"
    local list_rand="$((RANDOM % $list_count + 1))"
    local IFS=$'\n'
    set -- $MODEL_LIST
    MODEL="$(eval echo \${$list_rand})"
    set -- $PRODUCT_LIST
    PRODUCT="$(eval echo \${$list_rand})"
    DEVICE="$(echo "$PRODUCT" | sed 's/_beta//')"
  }
  set_random_beta
fi
echo " ➤ Using: $MODEL ($PRODUCT)"
echo " "

echo " ➤ Fetching latest Pixel Canary build info"
wget $WGET_Q -T 10 -O PIXEL_FLASH_HTML --no-check-certificate "https://flash.android.com/" || die "Failed to fetch flash tool page"

FLASH_KEY=$(grep -o '<body data-client-config=.*' PIXEL_FLASH_HTML | cut -d\; -f2 | cut -d\& -f1)
[ -z "$FLASH_KEY" ] && die "Failed to extract API key from flash tool"

wget $WGET_Q -T 10 -O PIXEL_STATION_JSON --header "Referer: https://flash.android.com" --no-check-certificate "https://content-flashstation-pa.googleapis.com/v1/builds?product=$PRODUCT&key=$FLASH_KEY" || die "Failed to fetch build data"

# Try canary first, then beta, then dev as fallback
BUILD_TYPE="canary"
tac PIXEL_STATION_JSON | grep -m1 -A13 '"canary": true' > PIXEL_CANARY_JSON 2>/dev/null
if [ ! -s PIXEL_CANARY_JSON ]; then
  BUILD_TYPE="beta"
  tac PIXEL_STATION_JSON | grep -m1 -A13 '"beta": true' > PIXEL_CANARY_JSON 2>/dev/null
fi
if [ ! -s PIXEL_CANARY_JSON ]; then
  BUILD_TYPE="dev"
  tac PIXEL_STATION_JSON | grep -m1 -A13 '"dev": true' > PIXEL_CANARY_JSON 2>/dev/null
fi

if [ ! -s PIXEL_CANARY_JSON ]; then
  warn "No canary, beta, or dev builds found for $PRODUCT"
  warn "This device may not have preview builds available yet"
  # Try to extract any build info as last resort
  tac PIXEL_STATION_JSON | grep -m1 -A13 '"buildId"' > PIXEL_CANARY_JSON 2>/dev/null
  [ ! -s PIXEL_CANARY_JSON ] && die "No build data available for $PRODUCT"
fi

ID="$(grep 'releaseCandidateName' PIXEL_CANARY_JSON | cut -d\" -f4)"
INCREMENTAL="$(grep 'buildId' PIXEL_CANARY_JSON | cut -d\" -f4)"
[ -z "$ID" -o -z "$INCREMENTAL" ] && die "Failed to extract build info from JSON"

echo " ➤ Found: Android $(grep 'releaseTrackVersionName' PIXEL_CANARY_JSON | cut -d\" -f4) (${BUILD_TYPE})"
echo " "

FI="$(grep 'factoryImageDownloadUrl' PIXEL_CANARY_JSON | cut -d\" -f4)"
FI_HOST="$(echo "$FI" | sed 's;^.*://\(.*\)$;\1;' | cut -d/ -f1)"
FI_PATH="/$(echo "$FI" | sed 's;^.*://\(.*\)$;\1;' | cut -d/ -f2-)"

CANARY_REL_DATE="Unknown"
CANARY_EXP_DATE="Unknown"

if [ "$FI" -a "$FI_HOST" -a "$FI_PATH" ]; then
  nc $FI_HOST 80 <<EOF | tr -d '\r' > PIXEL_ZIP_HEADERS
HEAD $FI_PATH HTTP/1.1
Host: $FI_HOST
Connection: close

EOF
  if [ -f PIXEL_ZIP_HEADERS ] && grep -q 'Last-Modified' PIXEL_ZIP_HEADERS; then
    CANARY_REL_DATE="$(date -D '%a, %d %b %Y %H:%M:%S %Z' -d "$(grep -o 'Last-Modified.*' PIXEL_ZIP_HEADERS | cut -d\  -f2-)" '+%Y-%m-%d')"
    CANARY_EXP_DATE="$(date -D '%s' -d "$(($(date -D '%Y-%m-%d' -d "$CANARY_REL_DATE" '+%s') + 60 * 60 * 24 * 7 * 6))" '+%Y-%m-%d')"
    echo " ➤ Canary Released: $CANARY_REL_DATE"
    echo " ➤ Estimated Expiry: $CANARY_EXP_DATE"
  else
    warn "Failed to determine Release Date from HTTP headers"
  fi
else
  warn "Failed to extract Factory Image URL from JSON"
fi
echo " "

echo " ➤ Building pixel config"
cat <<EOF | tee pif.prop >/dev/null
MANUFACTURER=Google
MODEL=$MODEL
FINGERPRINT=google/$PRODUCT/$DEVICE:CANARY/$ID/$INCREMENTAL:user/release-keys
PRODUCT=$PRODUCT
DEVICE=$DEVICE
SECURITY_PATCH=2026-09-05
DEVICE_INITIAL_SDK_INT=32
EOF

for MIGRATE in migrate.sh /data/adb/modules/playintegrityfix/migrate.sh; do
  [ -f "$MIGRATE" ] && break
done
if [ -f "$MIGRATE" ]; then
  for OLDPIF in /data/adb/modules/playintegrityfix/custom.pif.prop /data/adb/modules/playintegrityfix/custom.pif.json; do
    [ -f "$OLDPIF" ] && break
  done
  if [ -f "$OLDPIF" ]; then
    grep -q '//"\*.security_patch"' $OLDPIF && PATCH_COMMENT=1
    grep -q '#\*.security_patch' $OLDPIF && PATCH_COMMENT=1
  else
    FORCE_STRONG=1
  fi
  if [ "$FORCE_STRONG" ]; then
    echo " ➤ Forcing configuration for <A13 PI Strong"
    ARGS="-a"
    PATCH_COMMENT=1
    spoofProvider=0
  else
    echo " ➤ Retaining existing configuration"
  fi
  echo " "

  echo " ➤ Generating custom.pif.prop"
  rm -f pif.json custom.pif.json custom.pif.prop
  sh $MIGRATE -i $ARGS pif.prop >/dev/null 2>&1
  if [ -n "$ARGS" ]; then
    grep_config() {
      if [ -f "$2" ]; then
        case $2 in
          *.json) grep -m1 "$1" $2 | cut -d\" -f4;;
          *.prop|*.txt) grep -m1 "$1=" "$2" | cut -d= -f2 | cut -d\# -f1 | sed 's/[[:space:]]*$//';;
        esac
      fi
    }
    ADVSETTINGS="verboseLogs spoofApps spoofBuild spoofProps spoofProvider spoofSignature spoofVendingFinger spoofVendingSdk spoofPixel"
    for SETTING in $ADVSETTINGS; do
      eval [ -z \"\$$SETTING\" ] \&\& $SETTING=$(grep_config "$SETTING" $OLDPIF)
      eval TMPVAL=\$$SETTING
      [ -n "$TMPVAL" ] && sed -i "s;\($SETTING=\).;\1$TMPVAL;" custom.pif.prop
    done
  fi
  [ "$PATCH_COMMENT" = 1 ] && sed -i 's;\*.security_patch;#\*.security_patch;' custom.pif.prop
  echo " " >> custom.pif.prop
  echo "# Generated by IntegrityBox on $(date '+%Y-%m-%d')" >> custom.pif.prop
  echo " " >> custom.pif.prop
  echo "# Released On: $CANARY_REL_DATE" >> custom.pif.prop
  echo "# Estimated Expiry: $CANARY_EXP_DATE" >> custom.pif.prop
  cat custom.pif.prop >/dev/null 2>&1
fi

if [ "$DIR" = /data/adb/modules/playintegrityfix/osm0sis ]; then
  if [ -f /data/adb/modules/playintegrityfix/migrate.sh ]; then
    NEWNAME="custom.pif.prop"
  else
    NEWNAME="pif.prop"
  fi
  for OLDPIF in $NEWNAME custom.pif.json; do
    if [ -f "../$OLDPIF" ]; then
      echo " ➤ Backing-up current config"
      mv -fv ../$OLDPIF ../$OLDPIF.bak >/dev/null 2>&1
    fi
  done
  echo " ➤ Installing new config"
  cp -fv $NEWNAME .. >/dev/null 2>&1
fi

export_json_from_prop >/dev/null 2>&1
echo " "
echo " "
