#!/system/bin/sh

# This file is primarily adapted from PlayIntegrityFork
# Original repository: https://github.com/osm0sis/PlayIntegrityFork
#
# Minor modifications by: https://github.com/MeowDump
#
# Copyright (C) 2026 Original author of PlayIntegrityFork (https://github.com/osm0sis)
#
# Licensed under GNU GPL‑3.0 ~ see LICENSE file for details.

[ "$VERBOSE_MODE" = 1 ] && set -x

until [ -z "$1" ]; do
  case "$1" in
    -h|--help|help)
      echo "sh osm0sis.sh [-a|-s] [-m] [-n] [-x] [-k] [-v] [-S]"
      exit 0
      ;;
    -a|--advanced|advanced)
      ARGS="-a"; shift;;
    -s|--strong|strong)
      FORCE_STRONG=1; shift;;
    -m|--match|match)
      FORCE_MATCH=1; shift;;
    -n|--skip-json|skip-json)
      SKIP_JSON=1; shift;;
    -x|--skip-patch|skip-patch)
      SKIP_PATCH=1; shift;;
    -k|--skip-keybox|skip-keybox)
      SKIP_KEYBOX=1; shift;;
    -v|--verbose|verbose)
      VERBOSE_MODE=1; shift;;
    -S|--force-spoof-off|force-spoof-off)
      FORCE_SPOOF_OFF=1; shift;;
    *)
      break;;
  esac
done

case "$0" in
  *.sh) DIR="$0";;
  *) DIR="$(lsof -p $$ 2>/dev/null | grep -o '/.*osm0sis.sh$')";;
esac;
DIR=$(dirname "$(readlink -f "$DIR")");

die() { echo "\nError: $@!"; exit 1; }
die_bb() { die "$@, install busybox"; }
warn() { echo "\nWarning: $@!"; }

export_json_from_prop() {
    [ "$SKIP_JSON" = 1 ] && return 0
    FLAG_FILE="/data/adb/Box-Brain/json"
    PROP_FILE="/data/adb/modules/playintegrityfix/custom.pif.prop"
    OUT_JSON="/sdcard/meow.json"

    [ ! -f "$FLAG_FILE" ] && return 0
    [ ! -f "$PROP_FILE" ] && return 0

    RELEASED_ON=""
    EXPIRY_DATE=""
    FIRST=1

    echo "{" > "$OUT_JSON"

    while IFS= read -r LINE; do
        case "$LINE" in
            "# Released On:"*)
                RELEASED_ON="${LINE#\# Released On: }"
                continue
                ;;
            "# Estimated Expiry:"*)
                EXPIRY_DATE="${LINE#\# Estimated Expiry: }"
                continue
                ;;
            ""|\#*) continue ;;
        esac

        case "$LINE" in
            *=*)
                KEY="${LINE%%=*}"
                VALUE="${LINE#*=}"

                KEY="${KEY#\*.}"
                KEY="${KEY#\*}"

                case "$KEY" in
                    build.id) KEY="BUILD.ID" ;;
                    security_patch) KEY="SECURITY_PATCH" ;;
                    api_level) KEY="API_LEVEL" ;;
                esac

                VALUE="${VALUE//\"/\\\"}"

                [ "$FIRST" -eq 0 ] && echo "," >> "$OUT_JSON"
                FIRST=0

                printf '  "%s": "%s"' "$KEY" "$VALUE" >> "$OUT_JSON"
                ;;
        esac
    done < "$PROP_FILE"

    echo "" >> "$OUT_JSON"
    echo "}" >> "$OUT_JSON"

    {
        [ -n "$RELEASED_ON" ] && echo "// Released On: $RELEASED_ON"
        [ -n "$EXPIRY_DATE" ] && echo "// Estimated Expiry: $EXPIRY_DATE"
        echo "// Generated by IntegrityBox on $(date '+%Y-%m-%d')"
    } >> "$OUT_JSON"

    chmod 0644 "$OUT_JSON"
}

find_busybox() {
  [ -n "$BUSYBOX" ] && return 0;
  local path;
  for path in /data/adb/modules/busybox-ndk/system/*/busybox /data/adb/magisk/busybox /data/adb/ksu/bin/busybox /data/adb/ap/bin/busybox; do
    if [ -f "$path" ]; then
      BUSYBOX="$path";
      return 0;
    fi;
  done;
  return 1;
}

if ! which wget >/dev/null || grep -q "wget-curl" $(which wget); then
  if ! find_busybox; then
    die_bb "wget not found";
  elif $BUSYBOX ping -c1 -s2 android.com 2>&1 | grep -q "bad address"; then
    die_bb "wget broken";
  else
    wget() { $BUSYBOX wget "$@"; }
  fi;
fi;

if date -D '%s' -d "$(date '+%s')" 2>&1 | grep -qE "bad date|invalid option"; then
  if ! find_busybox; then
    die_bb "date broken";
  else
    date() { $BUSYBOX date "$@"; }
  fi;
fi;

if ! echo "A\nB" | grep -m1 -A1 "A" | grep -q "B"; then
  if ! find_busybox; then
    die_bb "grep broken";
  else
    grep() { $BUSYBOX grep "$@"; }
  fi;
fi;

if [ "$DIR" = /data/adb/modules/playintegrityfix ]; then
  DIR=$DIR/osm0sis;
  mkdir -p $DIR;
fi;
cd "$DIR";

echo " ➤ Fetching Pixel Beta device list";
LATEST_BETA=$(grep -B4 -A2 'data-icon=\"preview' PIXEL_VERSIONS_HTML | grep -o 'href="/about/versions/.*[0-9]"' | cut -d\" -f2);
[ "$LATEST_BETA" ] || LATEST_BETA=$(grep -oE 'href="/about/versions/[0-9]{2}"' PIXEL_VERSIONS_HTML | cut -d\" -f2 | sort -ru | head -n1 | tail -n1);
wget -q -O PIXEL_LATEST_HTML --no-check-certificate "https://developer.android.com$LATEST_BETA" 2>&1 || exit 1;
IS_QPR=qpr; grep -o 'href=".*download.*"' PIXEL_LATEST_HTML | grep -q 'qpr' || IS_QPR='.*';
wget -q -O PIXEL_FI_HTML --no-check-certificate "https://developer.android.com$(grep -o 'href=".*download.*"' PIXEL_LATEST_HTML | grep -v 'ota' | grep "$IS_QPR" | cut -d\" -f2 | head -n1 | tail -n1)" 2>&1 || exit 1;
wget -q -O PIXEL_OTA_HTML --no-check-certificate "https://developer.android.com$(grep -o 'href=".*download-ota.*"' PIXEL_LATEST_HTML | grep "$IS_QPR" | cut -d\" -f2 | head -n1 | tail -n1)" 2>&1 || exit 1;
SRC=FI; [ "$(grep 'tr id=' PIXEL_FI_HTML | sed 's;.*<tr id="\(.*\)">.*;\1;' | wc -w)" -lt "$(grep 'tr id=' PIXEL_OTA_HTML | sed 's;.*<tr id="\(.*\)">.*;\1;' | wc -w)" ] && SRC=OTA;
MODEL_LIST="$(grep -A1 'tr id=' PIXEL_FI_HTML | grep 'td' | sed 's;.*<td>\(.*\)</td>;\1;')";
PRODUCT_LIST="$(grep 'tr id=' PIXEL_FI_HTML | sed 's;.*<tr id="\(.*\)">;\1_beta;')";

if [ "$FORCE_MATCH" ]; then
  DEVICE="$(getprop ro.product.device)";
  case "$(echo ' '$PRODUCT_LIST' ')" in
    *" ${DEVICE}_beta "*)
      MODEL="$(getprop ro.product.model)";
      PRODUCT="${DEVICE}_beta";
    ;;
  esac;
fi;
echo " ➤ Selecting Pixel Beta device";
if [ -z "$PRODUCT" ]; then
  set_random_beta() {
    local list_count="$(echo "$MODEL_LIST" | wc -l)";
    local list_rand="$((RANDOM % $list_count + 1))";
    local IFS=$'\n';
    set -- $MODEL_LIST;
    MODEL="$(eval echo \${$list_rand})";
    set -- $PRODUCT_LIST;
    PRODUCT="$(eval echo \${$list_rand})";
    DEVICE="$(echo "$PRODUCT" | sed 's/_beta//')";
  }
  set_random_beta;
fi;
echo " ➤ Using: $MODEL ($PRODUCT)";
echo " "

echo " ➤ Fetching latest Pixel Canary build info";
wget -q -O PIXEL_FLASH_HTML --no-check-certificate "https://flash.android.com/" >/dev/null 2>&1 || exit 1;
wget -q -O PIXEL_STATION_JSON --header "Referer: https://flash.android.com" --no-check-certificate "https://content-flashstation-pa.googleapis.com/v1/builds?product=$PRODUCT&key=$(grep -o '<body data-client-config=.*' PIXEL_FLASH_HTML | cut -d\; -f2 | cut -d\& -f1)" >/dev/null 2>&1 || exit 1;
tac PIXEL_STATION_JSON | grep -m1 -A13 '"canary": true' > PIXEL_CANARY_JSON;
ID="$(grep 'releaseCandidateName' PIXEL_CANARY_JSON | cut -d\" -f4)";
INCREMENTAL="$(grep 'buildId' PIXEL_CANARY_JSON | cut -d\" -f4)";
[ -z "$ID" -o -z "$INCREMENTAL" ] && die "Failed to extract build info from JSON";
echo " ➤ Found: Android $(grep 'releaseTrackVersionName' PIXEL_CANARY_JSON | cut -d\" -f4)";
echo " "

FI="$(grep 'factoryImageDownloadUrl' PIXEL_CANARY_JSON | cut -d\" -f4)";
FI_HOST="$(echo "$FI" | sed 's;^.*://\(.*\)$;\1;' | cut -d/ -f1)";
FI_PATH="/$(echo "$FI" | sed 's;^.*://\(.*\)$;\1;' | cut -d/ -f2-)";
if [ "$FI" -a "$FI_HOST" -a "$FI_PATH" ]; then
  nc $FI_HOST 80 <<EOF | tr -d '\r' > PIXEL_ZIP_HEADERS;
HEAD $FI_PATH HTTP/1.1
Host: $FI_HOST
Connection: close

EOF
else
  warn "Failed to extract Factory Image URL from JSON";
fi;
if [ -f PIXEL_ZIP_HEADERS ] && grep -q 'Last-Modified' PIXEL_ZIP_HEADERS; then
  CANARY_REL_DATE="$(date -D '%a, %d %b %Y %H:%M:%S %Z' -d "$(grep -o 'Last-Modified.*' PIXEL_ZIP_HEADERS | cut -d\  -f2-)" '+%Y-%m-%d')";
  CANARY_EXP_DATE="$(date -D '%s' -d "$(($(date -D '%Y-%m-%d' -d "$CANARY_REL_DATE" '+%s') + 60 * 60 * 24 * 7 * 6))" '+%Y-%m-%d')";
  echo " ➤ Canary Released: $CANARY_REL_DATE";
  echo " ➤ Estimated Expiry: $CANARY_EXP_DATE";
else
  warn "Failed to determine Release Date from HTTP headers";
  CANARY_REL_DATE="Unknown";
  CANARY_EXP_DATE="Unknown";
fi;
echo " "

echo " ➤ Building pixel config";
cat <<EOF | tee pif.txt >/dev/null;
MANUFACTURER=Google
MODEL=$MODEL
FINGERPRINT=google/$PRODUCT/$DEVICE:CANARY/$ID/$INCREMENTAL:user/release-keys
PRODUCT=$PRODUCT
DEVICE=$DEVICE
SECURITY_PATCH=2026-06-01
DEVICE_INITIAL_SDK_INT=32
EOF

for MIGRATE in migrate.sh /data/adb/modules/playintegrityfix/migrate.sh; do
  [ -f "$MIGRATE" ] && break; 
done;
if [ -f "$MIGRATE" ]; then
  for OLDPIF in /data/adb/modules/playintegrityfix/custom.pif.prop /data/adb/modules/playintegrityfix/custom.pif.json; do
    [ -f "$OLDPIF" ] && break;
  done;
  if [ -f "$OLDPIF" ]; then
    grep -q '//"\*.security_patch"' $OLDPIF && PATCH_COMMENT=1;
    grep -q '#\*.security_patch' $OLDPIF && PATCH_COMMENT=0;
  else
    FORCE_STRONG=1;
  fi;
  if [ "$FORCE_STRONG" ]; then
    echo " ➤ Forcing configuration for <A13 PI Strong";
    ARGS="-a"; PATCH_COMMENT=1; spoofProvider=0;
  else
    echo " ➤ Retaining existing configuration";
  fi;
  echo " "

  echo " ➤ Generating custom.pif.prop";
  rm -f pif.json custom.pif.json custom.pif.prop;
  sh $MIGRATE -i $ARGS pif.txt >/dev/null 2>&1;
  if [ -n "$ARGS" ]; then
    grep_config() {
      if [ -f "$2" ]; then
        case $2 in
          *.json) grep -m1 "$1" $2 | cut -d\" -f4;;
          *.txt) grep -m1 "$1=" "$2" | cut -d= -f2 | cut -d\# -f1 | sed 's/[[:space:]]*$//';;
        esac;
      fi;
    }
    ADVSETTINGS="verboseLogs spoofApps spoofBuild spoofProps spoofProvider spoofSignature spoofVendingFinger spoofVendingSdk spoofPixel";
    for SETTING in $ADVSETTINGS; do
      eval [ -z \"\$$SETTING\" ] \&\& $SETTING=$(grep_config "$SETTING" $OLDPIF);
      eval TMPVAL=\$$SETTING;
      [ -n "$TMPVAL" ] && sed -i "s;\($SETTING=\).;\1$TMPVAL;" custom.pif.prop;
    done;
  fi;
  [ "$PATCH_COMMENT" ] && sed -i 's;^#\*.security_patch;*.security_patch;' custom.pif.prop;
  echo " " >> custom.pif.prop;
  echo "# Released On: $CANARY_REL_DATE" >> custom.pif.prop;
  echo "# Estimated Expiry: $CANARY_EXP_DATE" >> custom.pif.prop
  cat custom.pif.prop >/dev/null 2>&1;
fi;

if [ "$DIR" = /data/adb/modules/playintegrityfix/osm0sis ]; then
  if [ -f /data/adb/modules/playintegrityfix/migrate.sh ]; then
    NEWNAME="custom.pif.prop";
  else
    NEWNAME="pif.txt";
  fi;
  for OLDPIF in $NEWNAME custom.pif.json; do
    if [ -f "../$OLDPIF" ]; then
      echo " ➤ Backing-up current config";
      mv -fv ../$OLDPIF ../$OLDPIF.bak >/dev/null 2>&1;
    fi;
  done;
  echo " ➤ Installing new config";
  cp -fv $NEWNAME .. >/dev/null 2>&1;
fi;

export_json_from_prop >/dev/null 2>&1
echo " "
echo " "
